--Creating all the tables--
CREATE TABLE USERS(
  U_ID VARCHAR(10) PRIMARY KEY,
  U_FIRSTNAME VARCHAR NOT NULL,
  U_LASTNAME VARCHAR NOT NULL,
  U_PHONE NUMERIC NOT NULL,
  U_MAIL VARCHAR NOT NULL,
  U_NATION VARCHAR NOT NULL,
  U_AGE INTEGER NOT NULL,
  CHECK(U_AGE >= 19),
  PLAYER BOOL,
  COACH BOOL
);

CREATE TABLE ROLES(
  U_ID VARCHAR NOT NULL,
  R_ID VARCHAR(10) PRIMARY KEY NOT NULL,
  FOREIGN KEY(R_ID) REFERENCES USERS(U_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  BATSMAN BOOL,
  BOWLER BOOL,
  ALLROUNDER BOOL,
  WICKETKEEPER BOOL,
  CAPTAIN BOOL
);

CREATE TABLE LEAGUE(
  B_ID VARCHAR NOT NULL,
  L_ID VARCHAR (10) PRIMARY KEY NOT NULL,
  FOREIGN KEY(L_ID) REFERENCES BOARD(B_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  L_NAME VARCHAR NOT NULL,
  L_NATION VARCHAR NOT NULL,
  L_STARTDATE DATE NOT NULL,
  L_ENDDATE DATE NOT NULL,
  L_TYPE VARCHAR NOT NULL
);

CREATE TABLE TEAM(
  L_ID VARCHAR NOT NULL,
  T_ID VARCHAR (10) PRIMARY KEY NOT NULL,
  T_NAME VARCHAR NOT NULL,
  T_CAPTAIN VARCHAR NOT NULL,
  T_COACH VARCHAR NOT NULL,
  FOREIGN KEY(T_ID) REFERENCES LEAGUE(L_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BOARD(
  -- THIS TABLES GIVE INFORMATION ABOUT CRICKET COUNCIL BOARDS
  U_ID VARCHAR NOT NULL,
  B_ID VARCHAR PRIMARY KEY NOT NULL,
  FOREIGN KEY(B_ID) REFERENCES USERS(U_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  B_NAME VARCHAR NOT NULL
);

CREATE TABLE MATCHES(
  -- THIS TABLES GIVE INFORMATION ABOUT MATCHES
  L_ID VARCHAR NOT NULL,
  M_ID VARCHAR PRIMARY KEY NOT NULL,
  FOREIGN KEY(M_ID) REFERENCES LEAGUE(L_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  MATCH_TYPE VARCHAR NOT NULL,
  TEAM1 VARCHAR NOT NULL,
  TEAM2 VARCHAR NOT NULL,
  VENUE VARCHAR NOT NULL,
  MATCH_DATE DATE NOT NULL
);

CREATE TABLE PLAYER_PERFORMANCE(
  -- THIS TABLES GIVES THE PLAYER PERFORMANCE
  U_ID VARCHAR(10) NOT NULL,
  M_ID VARCHAR NOT NULL,
  RUN_SCORED INTEGER,
  BALL_FACED INTEGER,
  WICKET_TAKEN INTEGER,
  RUN_CONCEDED INTEGER,
  CATCHES INTEGER,
  STUMPS_TAKEN INTEGER,
  FOREIGN KEY (U_ID) REFERENCES USERS(U_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (M_ID) REFERENCES MATCHES(M_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TEAM_PERFORMANCE(
  T_ID VARCHAR NOT NULL,
  L_ID VARCHAR NOT NULL,
  MATCHES_PLAYED INTEGER NOT NULL,
  MATCHES_WON INTEGER NOT NULL,
  MATCHES_LOST INTEGER NOT NULL,
  MATCHES_TIED INTEGER NOT NULL,
  FOREIGN KEY(T_ID) REFERENCES TEAM(T_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(L_ID) REFERENCES LEAGUE(L_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

--Adding dummy data--

INSERT INTO USERS(U_ID, U_FIRSTNAME, U_LASTNAME, U_PHONE, U_MAIL, U_NATION, U_AGE, PLAYER, COACH)
VALUES
('U001', 'John', 'Doe', 1234567890, 'johndoe@email.com', 'USA', 30, true, false),
('U002', 'Jane', 'Doe', 9876543210, 'janedoe@email.com', 'USA', 27, true, false),
('U003', 'Bob', 'Smith', 5551234567, 'bobsmith@email.com', 'Canada', 25, true, false),
('U004', 'Alice', 'Johnson', 9995551111, 'alicejohnson@email.com', 'Canada', 22, true, false),
('U005', 'Sam', 'Lee', 1112223333, 'samlee@email.com', 'South Korea', 24, true, false);

INSERT INTO ROLES (U_ID, R_ID, BATSMAN, BOWLER, ALLROUNDER, WICKETKEEPER, CAPTAIN)
VALUES 
  ('U001', 'R001', true, false, true, false, true),
  ('U002', 'R002', true, true, true, true, false),
  ('U003', 'R003', true, true, false, false, false),
  ('U004', 'R004', false, true, false, true, false),
  ('U005', 'R005', true, true, true, false, true);