CREATE TABLE DUMMY (D_ID VARCHAR,D_NAME VARCHAR,D_COURSE VARCHAR);
CREATE TABLE COURSE (D_COURSE VARCHAR,C_NAME VARCHAR);

INSERT INTO COURSE(D_COURSE,C_NAME) VALUES
	('C1','AOA'),
	('C2','OS');

INSERT INTO DUMMY (D_ID,D_NAME,D_COURSE)VALUES
	(1,'AAA','C1'),
	(2,'BBB','C1'),
	(3,'CCC','C2'),
	(4,'DDD','C2');
SELECT * FROM DUMMY;

SELECT * FROM DUMMY
WHERE D_COURSE='C1';

ALTER TABLE DUMMY ADD PRIMARY KEY(D_ID);
ALTER TABLE COURSE ADD PRIMARY KEY(D_COURSE);
ALTER TABLE DUMMY ADD FOREIGN KEY(D_COURSE) REFERENCES COURSE(D_COURSE);

SELECT D_ID,D_NAME 
FROM DUMMY
WHERE D_COURSE IN
(
	SELECT D_COURSE 
	FROM COURSE 
	WHERE C_NAME='OS'
);